Assets/Plugins/Colyseus/Client.cs

**PROBLEM:** I was unable to get the error message when tapping into `onError`
**SOLUTION:** Set the type as `ErrorEventArgs` to be able to access `e.message`
```
client.OnError += (object sender, ErrorEventArgs e) => {
Debug.Log(e.message);
};
```

Set the type for onError to ErrorEventArgs

---

Assets/Plugins/Colyseus/Client.cs
Assets/Plugins/Colyseus/Room.cs
Assets/Plugins/Colyseus/Utils/ObjectExtensions.cs

The commented method GetAvailableRooms was not working because of Type Casting issue causing due to 
Convert.ChangeType, for slove this I have created a custom class to convert the incoming data to object in the required format.

Fix GetAvailableRooms method

---

Assets/Plugins/Colyseus/Client.cs
Assets/Plugins/Colyseus/Room.cs

Changed Recv to read all messages instead of one in a frame.
as discussed in discord.
It improved the ping in our game.
Another possible improvement, in the same manner, would be to parse the messages right away here:
https://github.com/colyseus/colyseus-unity3d/blob/adde79f0bdb1bda68fa79af90e363ee036fc0ef4/Assets/Plugins/WebSocket/WebSocket.cs#L234
and not on Recv(which might slow the update and fps).

better ping - reading all messages in one frame instead of one message a frame

---

Assets/Plugins/Colyseus/Serializer/Schema/Schema.cs

Fixes @etherny's latest bug report
- Uses `Dictionary<int, T>` internally for `ArraySchema`
- Implement `ForEach` method on `ArraySchema` and `MapSchema`

use Dictionary for ArraySchema internally to prevent duplicated entries

---

Assets/Plugins/Colyseus/Serializer/Schema/Schema.cs

It looks like this code may have been copied from SchemaArray, but the internal item store doesn't use the same iteration class for items. I'm not super familiar with this class, but here is my fix, which seems to work.

fixes invalid cast error

---

Assets/Plugins/WebSocket/WebSocket.cs

The PR Goal is to stabilize the the rooms underlying WebSocket connection.
In our project my task was to improve the re-connection ability of the connection. We plan to deploy the project for mobile devices.
There are some cases, when the server closes connection, however the client still thinks the connection is at open state, or took a long time to realize a problem has occurred. Through out of my experience with the framework, I've encounters the following problems.
Most of the time the problem was, the `Room` didn't get notified about the WebSocket `connectionState` change, so the `OnLeave` event never fired.
- Client side, the user turns off the wifi manually - connection shows open state forever. My solution was to detect this state manually, then Forcefully call the …

websocket stabilize - format code

---

README.md

First part for https://github.com/colyseus/colyseus-unity3d/issues/92
It describes how to release the repo with CI/CD
The CI/CD which was created takes the assets/plugins folder and adds it as a single zip attachment
suggestion: squash merge so history is not so full with update readme

add build badge and how to release description

---

Assets/Plugins/Colyseus/Client.cs
Assets/Plugins/WebSocket/WebSocket.cs

* Unawaited async method.
* Unused `e`.

Fix warnings.

---

Assets/Plugins/WebSocket/WebSocket.cs

The lack of the second parameter in the constructor for WebSocket on WebGL would cause the build pipeline to fail. This looks related to the recent addition to enable custom headers. This PR doesn't fully-implement the same functionality on WebGL builds, but does fix the build.

Add missing WebSocket parameter to constructor

---

Assets/Plugins/Colyseus/Room.cs
Assets/Plugins/Colyseus/Utils/ArrayUtils.cs

Now it is possible to send message type strings over 32+ characters :)

[Fix] Message type size over 32 characters wrong encoding

---

Assets/Colyseus/Runtime/Example~/Scripts/ExampleManager.cs
Assets/Colyseus/Runtime/Scripts/Managers/ColyseusManager.cs

Example code had old comment for ConnectToServer in place for InitializeClient calls. OverrideSettings also was sporadically failing to have the ColyseusRequest use the correct, new settings.  Added Example function to CreateNewRoom with roomOptions dictionary

Updated Example comment, OverrideSettings bug fix

---

Assets/Colyseus/Runtime/Example~/Scripts/ExampleRoomController.cs
Assets/Colyseus/Runtime/Scripts/Models/ColyseusConnection.cs
Assets/Colyseus/Runtime/Scripts/Room/ColyseusRoom.cs
Assets/Colyseus/Runtime/WebSocket/WebSocket.cs

Socket closure events now pass around the int code instead of the parsed enum value. This will cause errors anywhere that you have created custom `_room.colyseusConnection.OnClose` / `_room.colyseusConnection.OnLeave` events that are anticipating a `WebSocketCloseCode` argument rather than an int. The `WebSocketCloseCode` can still be obtained via `WebSocketHelpers.ParseCloseCodeEnum(code)`

Enhancement/Bug 157 Adjustment

---

Assets/Colyseus/Runtime/Scripts/ColyseusRequest.cs
Assets/Colyseus/Runtime/Scripts/Managers/ColyseusManager.cs
Assets/Colyseus/Runtime/Scripts/Models/ColyseusClient.cs
Assets/Colyseus/Runtime/Scripts/Settings/ColyseusSettings.cs

Fixes https://github.com/colyseus/colyseus-unity3d/issues/156
Resolves issue of ColyseusRequest only working with a single instance of settings due to its static nature.
ColyseusRequest is now no longer has static methods. Moved the requests object out of ColyseusManager and into ColyseusClient. Each client now has its own instance of ColyseusRequest that can be initialized with its own endpoint or ColyseusSettings.

Bug 156 Adjustment

---

Assets/Colyseus/Runtime/Scripts/ColyseusRequest.cs

Brought in changes from PR 167 but added the preprocessing commands to support lower versions than Unity 2020

Fixing usage of deprecated UnityWebRequest methods

---

Assets/Colyseus/Runtime/Scripts/ColyseusRequest.cs

Use using declaration to handle disposal of UnityWebRequest objects.
Fixes https://github.com/colyseus/colyseus-unity3d/issues/160

Dispose UnityWebRequest objects in ColyseusRequest.cs

---

Assets/Colyseus/Runtime/Scripts/ColyseusRequest.cs

"using" was throwing errors in Unity versions prior to 2020.2, when C# 8.0 was introduced

Added precompiler directives before using declaration

---

Assets/Colyseus/Runtime/Scripts/Serializer/Schema/Types/ColyseusReflection.cs

This issue has been reported recently. Happening only on WebGL builds. 
```
OverflowException: Value was either too large or too small for an Int32.
at System.Convert.ToInt32 (System.Double value) [0x00000] in <00000000000000000000000000000000>:0 
```
After inspecting, it has been found out that the error happened during schema serializer's `Handshake`, where `fieldsByIndex` did not contain one of the fields defined via `[Type()]` annotation: 
https://github.com/colyseus/colyseus-unity3d/blob/f80f7f402ad2e51c4ebad59db389c0b4d05ee1ad/Assets/Colyseus/Runtime/Scripts/Serializer/Schema/Schema.cs#L430
This PR fixes the issue.

prevent properties from being stripped out of WebGL builds.

---

Assets/Colyseus/Runtime/Scripts/Models/ColyseusErrorCode.cs
Assets/Colyseus/Runtime/Scripts/Models/ColyseusErrorCode.cs.meta
Assets/Colyseus/Runtime/Scripts/Room/ColyseusRoom.cs

In case of schema mismatch the ConsumeSeatReservation Task was stuck forever. This is because the OnError callback which would complete the task was never called. Also the player is still in the room but unable to do anything.
Those commits are a simple fix, now the schema mismatch exception will be thrown and player will automatically leave the room.

Fix schema mismatch exception

---

Assets/Colyseus/Runtime/Scripts/ColyseusRequest.cs
Assets/Colyseus/Runtime/Scripts/Models/ColyseusClient.cs
Assets/Colyseus/Runtime/Scripts/Settings/ColyseusSettings.cs

Implemented fix to allow the use of an additional path appended to the host of the server address.  The path included in the server address is now included in the websocket and web request endpoints.

Allow use of path appended to server address

---

Assets/Colyseus/Tests/Editor/ServerSettingsEditor.cs

Fix error log showing every time Unity refreshes. Added a check if the directory path to the icon exists in Assets directory otherwise use the Packages directory.

Fix error log showing every time when Unity refreshes

---

Assets/Colyseus/Runtime/Scripts/Serializer/ColyseusSchemaSerializer.cs

This fixes backward compatibility, at the cost of having potential false positives
Related: #205

fix: schema mismatch as warning

---

Assets/Colyseus/Runtime/GameDevWare.Serialization/Metadata/MetadataReflection.cs

This is fix for 'unable to find default constructor to type 'X' for AOT runtimes like iOS, WebGL etc.

fix constructor lookup for AOT runtime

---

Assets/Colyseus/Runtime/Colyseus/Serializer/Schema/Types/ArraySchema.cs

InvokeOnAdd is call pass arguments in the wrong order

fix order of arguments on ArraySchema.OnAdd triggerAll

---

Assets/Colyseus/Runtime/Colyseus/Room/ColyseusRoom.cs

Unity clients can now receive data sent from the server using client.sendBytes.
For a Unity client to register a call back for a message sent to it by the server using SendBytes, call RoomController OnMessage with the type byte[ ]

Implemented parsing of ROOM_DATA_BYTES

---

Assets/Colyseus/Runtime/Colyseus/Serializer/Schema/Types/ArraySchema.cs
Assets/Colyseus/Runtime/Colyseus/Serializer/Schema/Types/MapSchema.cs

Copy reference to internal indexes dictionary during clone of ArraySchema and MapSchema.
Fixes [#230](https://github.com/colyseus/colyseus-unity-sdk/issues/230).

Fix cloning of ArraySchema and MapSchema

---

Assets/Colyseus/Runtime/WebSocket/WebSocket.cs

The issue was explain in [issue report](https://github.com/colyseus/colyseus-unity-sdk/issues/232)
I test this in 0.14.21 but this file is the same on master, and I think that it's good to release resource in any case.

Try to fix no more messages sent after exception.

---

Assets/Colyseus/Runtime/Colyseus/Serializer/Schema/Types/ArraySchema.cs
Assets/Colyseus/Runtime/Colyseus/Serializer/Schema/Types/MapSchema.cs

Prevent the compiler from stripping the empty constructors for Array and Map Schema in IL2CPP builds.
Fixes #254

Avoid Constructor Stripping for ArraySchema & MapSchema
